general_perplexity_prompt = "Imagine you are world's foremost expert on cryptocurrencies and you specialise in being able to decipher their white papers. Please summarize the cryptocurrency whitepaper by addressing the following questions: What problem does the project aim to solve? Who is the target audience for this project? How does the project plan to achieve mass adoption? What are the technical details of the project? How is the project's network secured? What is the project's governance model? How does the project plan to handle regulatory compliance?"
competitor_perplexity_prompt = "Imagine you are world's foremost expert on cryptocurrencies and you specialise in being able to decipher their white papers. Please summarize the cryptocurrency whitepaper by addressing the following questions: Who are the project's competitors? How does the project distinguish itself from its competitors? What are the project's key strengths and weaknesses? What potential risks and challenges does the project face? How does the project's revenue model compare to that of its competitors?"
community_perplexity_prompt = "Imagine you are world's foremost expert on cryptocurrencies and you specialise in being able to decipher their white papers. Please summarize the cryptocurrency whitepaper by addressing the following questions: What is the project's community engagement strategy?How does the project plan to handle community governance? - If applicable (for DAO’s) What are the project's marketing and PR strategies? How does the project plan to build its brand? What is the project's approach to user experience? How does the project plan to handle user support? What is the project's approach to interoperability? How does the project plan to handle cross-chain compatibility? What is the project's approach to scalability?"
platform_and_data_perplexity_prompt = "Imagine you are world's foremost expert on cryptocurrencies and you specialise in being able to decipher their white papers. Please summarize the cryptocurrency whitepaper by addressing the following questions: Describe how the project plans to handle transaction speed and throughput. What is the project's approach to smart contract development? How does the project address potential security vulnerabilities? Explain the project's methods for data storage and retrieval. Discuss how the project intends to manage data analysis. Detail the project’s strategies for ensuring data privacy and security. What measures does the project have in place for user privacy, including how user data is handled in terms of consent, ownership, control, access, sharing, protection, deletion, retention, backup, recovery, encryption, decryption, integrity, and authenticity? Specifically, how does the project ensure the authenticity of user data?"
tokenomics_perplexity_prompt = "Imagine you are world's foremost expert on cryptocurrencies and you specialise in being able to decipher their white papers. Please summarize the cryptocurrency whitepaper by addressing the following questions: How does the tokenomics model incentivize token holders to participate in the ecosystem? What mechanisms are in place to prevent token hoarding and encourage circulation? Can you explain the token utility within the ecosystem and how it drives value? How does the tokenomics design account for potential market fluctuations and volatility? What measures are in place to ensure a fair and transparent token distribution process? Can you elaborate on the token-burning mechanism and its impact on token supply? - If applicable  What role does staking play in the tokenomics model and how does it benefit participants? How does the token vesting schedule align with the project's long-term goals and sustainability? Can you explain the governance structure related to tokenomics decisions and changes? How does the tokenomics model address potential regulatory challenges and compliance requirements? - if applicable  What mechanisms are in place to ensure the security and integrity of the token ecosystem "
circulating_supply_perplexity_prompt = "Imagine you are world's foremost expert on cryptocurrencies and you specialise in being able to decipher their white papers. Please summarize the cryptocurrency whitepaper by addressing the following questions: Can you provide a breakdown of the token distribution among different stakeholder categories? Are there any planned or potential changes to the token's distribution or allocation model in the near future? How is the inflation rate of the token determined, and what factors could influence its trajectory over time? What is the expected yield for token holders based on the current revenue distribution model? Are there any mechanisms in place to ensure a fair and gradual release of the remaining tokens? How often is the token's vesting schedule reviewed or updated, and what triggers such revisions? What is the current circulating supply of the token? How is the token distributed and allocated among its stakeholders? Can a projection be made regarding the inflation rate of the token over 5 years? What is the Approximated Percentage Rate of revenue that can be earned from holding this token? How many tokens are yet to be released, and what is the vesting schedule associated with them?"
revenue_perplexity_prompt = "Imagine you are world's foremost expert on cryptocurrencies and you specialise in being able to decipher their white papers. Please summarize the cryptocurrency whitepaper by addressing the following questions: What is the primary revenue generation model for the project? How does the project plan to sustain its revenue stream over time? What is the expected revenue growth rate for the project? How does the project plan to address potential revenue fluctuations and market volatility? How does the project plan to expand its revenue streams over time? What is the project's revenue projection for the next 12 months, 2 years, and 5 years? How does the project's revenue model support its development roadmap and product development? What is the project's approach to managing revenue-related compliance and regulatory requirements? - If applicable"
team_perplexity_prompt = "Imagine you are world's foremost expert on cryptocurrencies and you specialise in being able to decipher their white papers. Please summarize the cryptocurrency whitepaper by addressing the following questions: What is the team's background and experience in the blockchain and crypto industry? How diverse is the team in terms of skills, expertise, and background? What is the team's track record in delivering successful projects in the past? How does the team's experience align with the project's goals and objectives? How does the team plan to manage and grow the project over time? How does the team plan to handle community feedback and suggestions How does the team's experience and expertise align with the project's regulatory and compliance requirements?"
partners_and_investors_prompt = "Imagine you are world's foremost expert on cryptocurrencies and you specialise in being able to decipher their white papers. Please summarize the cryptocurrency whitepaper by addressing the following questions: What strategic partnerships does the project have in place to enhance its ecosystem and reach? Who are the project's key investors, and what expertise or value do they bring to the table? What is the project's approach to attracting and retaining investors in the competitive crypto market? How does the project explain its token distribution strategy to investors in the whitepaper? What incentives does the project offer to investors to encourage participation and long-term commitment? How does the project prioritize investor protection and security of funds within the crypto ecosystem?"
final_summary_prompt= "Imagine you are world's foremost expert on cryptocurrencies and you specialise in being able to decipher their white papers. please reorder the text, and eliminate what is repeated. make it a complete text, without eliminating information or discarding important data. only orderly and eliminating repeated phrases."

def clean_summary(perplexity_result):
    summary = perplexity_result.get('response', '')
    parts = summary.split('titled "', 1)
    if len(parts) > 1:
        summary = parts[1].strip()
    final_summary = summary.replace('"', '')
    return final_summary 